linters:
  enable:
    - deadcode
    - errcheck
    - gas
    - goconst
    - gofmt
    - golint
    - gosimple
    - ineffassign
    - interfacer
    - lll
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - varcheck
    - vet
    - vetshadow
  enable-all: false
  timeout: 10m
